### ISSUE TITLE
krakend-rss example silently fails

### ISSUE THREAD

**Issue by sergeytsivin** [krakend/krakend-rss#1]
When I compile and run the example it exists with exit code 1 but no error is printed in the console

> mac-98450266:example stsivin$ make
> go get "github.com/devopsfaith/krakend/config"
> go get "github.com/devopsfaith/krakend/logging"
> go get "github.com/devopsfaith/krakend/proxy"
> go get "github.com/devopsfaith/krakend/router/gin"
> go build -ldflags="-X github.com/devopsfaith/krakend/core.KrakendVersion=0.5.0-1-g47ac2b1" -o krakend_rss_example_0.5.0-1-g47ac2b1
> You can now use ./krakend_rss_example_0.5.0-1-g47ac2b1
> mac-98450266:example stsivin$ ls -lt
> total 37448
> -rwxr-xr-x  1 stsivin  1096600021  19159676 14 сен 08:59 krakend_rss_example_0.5.0-1-g47ac2b1
> -rw-r--r--  1 stsivin  1096600021      1429 14 сен 08:56 main.go
> -rw-r--r--  1 stsivin  1096600021       916 14 сен 08:56 krakend.json
> -rw-r--r--  1 stsivin  1096600021       816 14 сен 08:56 Makefile
> mac-98450266:example stsivin$ ./krakend_rss_example_0.5.0-1-g47ac2b1 
> mac-98450266:example stsivin$

**Comment by sergeytsivin** [comment]
It turns out that krakend.json needs to be updated to verision 2, not sure why the error has not been printed out. 

I don't understand why the errors had not been printed in the first place, but once the logger initializations was moved up the following errors were printed:

> 2020/09/14 12:08:27 ERROR:'./krakend.json': json: cannot unmarshal number into Go struct field parseableServiceConfig.cache_ttl of type string, offset: 91, row: 4, col: 21

and then:

> 2020/09/14 12:12:25 ERROR:'./krakend.json': Unsupported version: 1 (want: 2)

**Comment by kpacha** [comment]
the example is very out of date. if you're interested on config examples, you can check out the one used at the integration tests: https://github.com/devopsfaith/krakend-ce/blob/master/tests/fixtures/krakend.json#L318-L356

**Comment by sergeytsivin** [comment]
@kpacha, thank you! I have made a PR #2 updating the example.
